{"name": "test_create_user_invalid_json", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'code' to be 400, got 401.", "trace": "def test_create_user_invalid_json():\n        \"\"\"Test case for creating a user - negative case with invalid JSON syntax.\"\"\"\n        step_name = \"Create User - Invalid JSON\"\n        request_data = \"\"\"{\n            \"name\": \"John Doe\",\n            \"email\": \"john.doe@example.com\",\n            \"gender\": \"male\",\n            \"status\": \"active\",\n        }\"\"\"\n    \n        log_request_data(request_data, step_name)\n    \n        response = requests.post(f\"{BASE_URL}/users\", data=request_data, headers=headers)\n    \n        log_response_data(response, step_name)\n    \n        expected_status_code = 200\n        expected_values = {\n            \"code\": 400,\n            \"meta\": None,\n            \"data\": {\n                \"message\": \"Error occurred while parsing request parameters\"\n            }\n        }\n    \n>       log_and_assert(response, expected_status_code, expected_values)\n\nsrc/test_api.py:94: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>\nexpected_status = 200\nexpected_values = {'code': 400, 'data': {'message': 'Error occurred while parsing request parameters'}, 'meta': None}\n\n    def log_and_assert(response, expected_status, expected_values):\n        \"\"\"\n        Log response and assert expected values.\n    \n        Parameters:\n        - response: The HTTP response object.\n        - expected_status: The expected HTTP status code.\n        - expected_values: A dictionary of expected values to assert in the response JSON.\n        \"\"\"\n    \n        log_response_data(response)\n        response_json = response.json()\n    \n        assert response.status_code == expected_status, f\"Expected status code {expected_status}, got {response.status_code}.\"\n    \n        for key, expected_value in expected_values.items():\n            actual_value = response_json.get(key)\n>           assert actual_value == expected_value, f\"Expected '{key}' to be {expected_value}, got {actual_value}.\"\nE           AssertionError: Expected 'code' to be 400, got 401.\n\nsrc/utils/logger_validator.py:30: AssertionError"}, "description": "Test case for creating a user - negative case with invalid JSON syntax.", "steps": [{"name": "Request for Create User - Invalid JSON", "status": "passed", "attachments": [{"name": "Create User - Invalid JSON", "source": "3a87bb5d-cfcb-4be2-aaf0-18ca4ff53105-attachment.json", "type": "application/json"}], "start": 1729049097383, "stop": 1729049097384}, {"name": "Response for Create User - Invalid JSON", "status": "passed", "attachments": [{"name": "Create User - Invalid JSON", "source": "fe88bdbc-7a0e-4164-b4ec-a960919bd522-attachment.json", "type": "application/json"}], "start": 1729049097565, "stop": 1729049097567}, {"name": "Response for Response", "status": "passed", "attachments": [{"name": "Response", "source": "94ae0987-75fc-4e9e-8815-e6865ac46723-attachment.json", "type": "application/json"}], "start": 1729049097567, "stop": 1729049097568}], "start": 1729049097383, "stop": 1729049097568, "uuid": "651018e5-e4b9-4ed2-a7a5-b90e41973117", "historyId": "7ca760caa22fab52195aec27251ef5d5", "testCaseId": "7ca760caa22fab52195aec27251ef5d5", "fullName": "src.test_api#test_create_user_invalid_json", "labels": [{"name": "parentSuite", "value": "src"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "Aras-MacBook-Air.local"}, {"name": "thread", "value": "32579-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.test_api"}]}